PACKLIST_BY_TYPE = {
    "general": [
        "Passport 🛂",
        "ID (Driver's License, REAL ID, etc.) 🪪",
        "Toothbrush 🪥",
        "Toothpaste 🦷",
        "Floss 🧵",
        "Deodorant 🧴",
        "Shampoo/Conditioner (travel size) 🧼",
        "Body wash or soap 🧽",
        "Hairbrush/Comb 💇",
        "Hair ties or clips 🪢",
        "Hand sanitizer 🧴",
        "Face masks 😷",
        "Medications (daily + extras) 💊",
        "Band-aids 🩹",
        "Pain relievers (Ibuprofen, Tylenol) 💊",
        "Menstrual Products 🩸",
        "Wallet 👛",
        "Credit/Debit cards 💳",
        "Cash (local currency + USD) 💵",
        "Phone 📱",
        "Phone charger 🔌",
        "Portable charger / power bank 🔋",
        "Charging cable (extra) 🪫",
        "Earbuds/Headphones 🎧",
        "Reusable water bottle 🍼",
        "Towel 🧺",
        "Socks 🧦",
        "Underwear 🩲",
        "T-shirts 👕",
        "Pants/Shorts 👖",
        "Sweater or Jacket 🧥",
        "Sleepwear 🛌",
        "Walking shoes 👟",
        "Snacks 🍫"
    ],
    "air": [
        "Visa (if needed) 📄",
        "Travel insurance card/documents 📝",
        "Printed copies of travel documents 📠",
        "Emergency contact list ☎️",
        "Travel itinerary 📅",
        "Hotel/Airbnb confirmations 🏨",
        "Boarding passes (printed or digital backup) 🎫",
        "Travel money pouch or belt 🎒",
        "Travel adapter/converter 🔌",
        "Power strip or outlet splitter 🔌",
        "Language phrasebook or translation app 🈯",
        "Backup SD card / storage for photos 💾",
        "E-reader or book 📚"
    ],
    "road": [
        "Phone mount 📱",
        "Car charger 🚗🔌",
        "Printed directions or map 🗺️",
        "Snacks (extra) 🍿",
        "Cooler 🧊",
        "Blanket 🛏️",
        "Flashlight 🔦",
        "Entertainment (audiobooks, music, etc.) 🎵",
        "Reusable shopping bag 🛍️",
        "Coins for tolls 🪙"
    ],
    "nature": [
        "Tent ⛺",
        "Sleeping bag 🛏️",
        "Sleeping pad or air mattress 🛌",
        "Camping pillow 🧻",
        "Tarp or ground cloth 🪵",
        "Lantern or headlamp 🏮",
        "Camp stove 🍳",
        "Fuel for stove ⛽",
        "Cooking utensils 🍴",
        "Mess kit (plate, bowl, utensils) 🍽️",
        "Camp chairs 🪑",
        "Fire starter (matches/lighter) 🔥",
        "Firewood (if allowed) 🌲",
        "Multi-tool or pocketknife 🛠️",
        "Trash bags 🗑️",
        "Rope or paracord 🪢",
        "Bug spray / insect repellent 🦟",
        "Toilet paper 🧻",
        "Camping permit (if needed) 🧾"
    ],
    "sun": [
        "Sunscreen (face & body) 🧴",
        "After-sun lotion (like aloe) 🌿",
        "Sunglasses 🕶️",
        "Sun hat 👒",
        "Swimsuit 🩱",
        "Swim cover-up 🧣",
        "Flip-flops 🩴",
        "Cooling towel 🧊",
        "Water shoes 🥾",
        "Beach umbrella 🏖️"
    ],
    "car": [
        "Driver’s license 🪪",
        "Car registration and insurance 📄",
        "Spare key 🔑",
        "Roadside emergency kit 🚨",
        "Jumper cables 🧲",
        "Tire pressure gauge 📏",
        "Windshield sun shade 🌞",
        "Gas can ⛽",
        "Wet wipes / napkins 🧻"
    ],
    "custom": []
}